// <auto-generated />
using System;
using MatrixInc.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatrixInc.DataAccess.Migrations
{
    [DbContext(typeof(MatrixDbContext))]
    [Migration("20260702022514_SplitAddressFields")]
    partial class SplitAddressFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Amsterdam",
                            Country = "Nederland",
                            HouseNumber = "1",
                            PostalCode = "1234AB",
                            Street = "Hoofdstraat"
                        },
                        new
                        {
                            Id = 2,
                            City = "Rotterdam",
                            Country = "Nederland",
                            HouseNumber = "25",
                            PostalCode = "5678CD",
                            Street = "Dorpsweg"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentNumber = "2B",
                            City = "Utrecht",
                            Country = "Nederland",
                            HouseNumber = "42",
                            PostalCode = "3456EF",
                            Street = "Kerkstraat"
                        });
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AddressOld")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            AddressOld = "Hoofdstraat 1, 1234AB Amsterdam",
                            CreatedDate = new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.bakker@example.com",
                            Name = "Jan Bakker",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            AddressOld = "Dorpsweg 25, 5678CD Rotterdam",
                            CreatedDate = new DateTime(2024, 9, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.devries@example.com",
                            Name = "Marie de Vries",
                            PhoneNumber = "0687654321"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            AddressOld = "Kerkstraat 42-2B, 3456EF Utrecht",
                            CreatedDate = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "piet.jansen@example.com",
                            Name = "Piet Jansen",
                            PhoneNumber = "0698765432"
                        });
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCourierId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tandwielen",
                            Description = "Hoogwaardig stalen tandwiel voor industriële toepassingen",
                            IsActive = true,
                            Name = "Tandwiel A200",
                            Price = 45.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 2,
                            Category = "Lagers",
                            Description = "Kogellager met hoge belastingscapaciteit",
                            IsActive = true,
                            Name = "Lager B350",
                            Price = 32.50m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bevestigingsmiddelen",
                            Description = "Zeskant moer M12 verzinkt",
                            IsActive = true,
                            Name = "Moer M12",
                            Price = 0.75m,
                            StockQuantity = 5000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bevestigingsmiddelen",
                            Description = "Zeskantbout M12x50 verzinkt",
                            IsActive = true,
                            Name = "Bout M12x50",
                            Price = 1.25m,
                            StockQuantity = 3000
                        },
                        new
                        {
                            Id = 5,
                            Category = "Koppelingen",
                            Description = "Flexibele koppeling voor asverbindingen",
                            IsActive = true,
                            Name = "Koppeling C450",
                            Price = 125.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 6,
                            Category = "Spindels",
                            Description = "Precisie spindel voor CNC machines",
                            IsActive = true,
                            Name = "Spindel D600",
                            Price = 850.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            Category = "Aandrijvingen",
                            Description = "V-snaar riemschijf 100mm diameter",
                            IsActive = true,
                            Name = "Riemschijf E100",
                            Price = 28.75m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pakkingen",
                            Description = "Rubber pakking 25mm",
                            IsActive = true,
                            Name = "Pakking F25",
                            Price = 3.50m,
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Customer", b =>
                {
                    b.HasOne("MatrixInc.DataAccess.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Order", b =>
                {
                    b.HasOne("MatrixInc.DataAccess.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.OrderItem", b =>
                {
                    b.HasOne("MatrixInc.DataAccess.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrixInc.DataAccess.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MatrixInc.DataAccess.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
